### ISSUE TITLE
Earthquake Research

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#13]
# Information Needed:

**Comment by rereshek** [comment]
[Earthquake Research.pdf](https://github.com/EricLacey/BadWeather/files/4140750/Earthquake.Research.pdf)

**Comment by rereshek** [comment]
Earthquake Research
Cause: 
Earthquakes are usually caused when rock underground suddenly breaks along a fault. This sudden release of energy causes the seismic waves that make the ground shake. The spot underground where the rock breaks is called the focus of the earthquake. The place right above the focus (on top of the ground) is called the epicenter of the earthquake.

Earthquake-like seismic waves can also be caused by explosions underground. These explosions may be set off to break rock while making tunnels for roads, railroads, subways, or mines. These explosions, however, don't cause very strong seismic waves. You may not even feel them. Sometimes seismic waves occur when the roof or walls of a mine collapse. These can sometimes be felt by people near the mine. The largest underground explosions, from tests of nuclear warheads (bombs), can create seismic waves very much like large earthquakes. This fact has been exploited as a means to enforce the global nuclear test ban, because no nuclear warhead can be detonated on earth without producing such seismic waves.

Effects: 
Many buildings, hospitals, schools, etc are destroyed due to it. A lot of people get killed and injured. Many people lose their money and property. It affects the mental health and emotional health of people.
The environmental effects of it are that including surface faulting, tectonic uplift and subsidence, tsunamis, soil liquefaction, ground resonance, landslides and ground failure, either directly linked to a quake source or provoked by the ground shaking.

Emergency response::
Move away from windows and doors. 
Drop to the floor, take cover under a sturdy table or desk against an inside wall. 
Grasp one of its legs while covering your head with your other arm. 
Expect fire alarms and sprinklers to go off. 
Do not use elevators. Stay inside until the shaking stops. DO NOT run outside.

Is it linked to climate change: debatable

“the only correlation that’s been noted between earthquakes and weather is that large changes in atmospheric pressure caused by major storms like hurricanes have been shown to occasionally trigger what are known as “slow earthquakes,” which release energy over comparatively long periods of time and don’t result in ground shaking like traditional earthquakes do”

“the low-pressure centers of typhoons can prompt vibrations of earthquake faults”
Where does this happen:
Prince Rupert, Quesnel and Houston, British Columbia.
Northwest Territories, southeastern Yukon, and northern Alberta and British Columbia.


Magnitude | Earthquake Effects | Estim # each year
-- | -- | --
<2.5 | Usually not felt | 900,000
2.5 to 5.4 | Often felt, but only causes minor damage. | 30,000
5.5 to 6.0 | Slight damage to buildings and other structures. | 500
6.1 to 6.9 | May cause a lot of damage in very populated areas. | 100
7.0 to 7.9 | Major earthquake. Serious damage. | 20
8.0 or greater | Great earthquake. Can totally destroy communities near the epicenter. | One every 5 to 10 years
