### ISSUE TITLE
Volcano Research

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#14]
# Information Needed:

**Comment by antoinella** [comment]
https://docs.google.com/document/d/1KqLLVOWrC44TZZJVfx0EHmr6478Iw8kM62GDcTocP3M/edit?usp=sharing

**Comment by antoinella** [comment]
VOLCANOES
What are the effects:
Covers objects with ash - ashfall can be heavy and make it hard to breathe
Lava flows, although slow, can still ruin houses, roads, and other objects (most people can out run this lava type)
Pyroclastic lava flows are more deadly because they travel faster. Mix of ash and hot gas and can kill you since you can’t outrun it fast enough (100-200 km/h)
Water contamination
damaged machinery
reduced visibility
difficulty breathing
irritation of skin, eyes, nose, throat
What is the emergency response:
Stay updated about volcanic activity warnings with http://volcanoes.usgs.gov/vns2/
Volcanoes with pyroclastic flows: leave ASAP before eruption
If volcano erupts nearby a city, civil defense authorities are consulted. Depends on size and type of eruption…
Listen for emergency info/alerts
Follow evacuation orders
Avoid areas headed towards eruption
Protect yourself from falling ash
Do not drive if ashfall is heavy. Ashes can clog engines and stall vehicles
If the biggest risk is ash: stay indoors at a safe temporary shelter if enough supplies. Seal doors/windows, cover vent openings
If biggest risk is lava: evacuate as far away as you can
Avoid areas with wind that can carry rubble/ash
If outside: try to use a certified face mask to protect yourself from falling ashes
Send texts to family/friends/social media. Calling may be too busy, unless you use emergency call
Do not get rid of ash from roof unless you have been trained
What causes it:
Volcanoes erupt when magma (molten rock), formed through melting of Earth’s mantle, starts rising to the surface
When Earth’s mantle melts, it’s because of the movement of tectonic plates (pulling/pushing away)
Since magma is lighter than rock, it rises above to the surface of earth, creating gas bubbles along the way. Thick magma has more gas bubbles.
If runny magma erupts from an opening, it runs on earth’s surface as lava
2 ways volcano has a deadly explosion:
When there is too much pressure from gas bubbles in thick magma
When there is too much pressure from subsurface water interacting with hot magma to create steam
Is it linked to climate change:
Something good: can make soil more fertile for farming. Something bad: can also kill crops
Volcanoes release less than 2% of carbon dioxide from human activities,
Although about once in 20 years there is a huge volcanic eruption that releases a large amount of gases. These gases protect earth against the sun better, causing global cooling for a couple of years
Mount Pinatubo erupted in philippines in 1991, 20 million tonnes of sulfur dioxide and ashes blasted 20km high into the sky. This caused cooler global temperatures, reduced solar radiation, and changed atmospheric circulation patterns.
Sulfuric gases change to sulfate aerosols particles that contain mainly sulfuric acid, which can stay trapped for a few years in the stratosphere
Volcanic aerosols can cause cooling of global troposphere, but warming of stratosphere, and warm troposphere in the winter
Where does this happen:
Where major tectonic plates shift
Most active volcanoes in: Alaska, Hawaii, California, Oregon
Kilauea continuously erupts
Tambora volcano in 1815 killed 10 000 people
1984: Mauna Loa erupted in Hawaii, but lava flows stopped before town
1973: Heimaey erupted in Iceland, burying nearby town of Heimaey
1960: Kilauea erupted in Hawaii, burying nearby town of Kapoho
1980: Mount St. Helens ashes fell all over Washington and Oregon towns
1902: Mount Pelee erupted in Martinique island, destroying Saint Pierre town
1985: Ruiz had lahars (destructive mudflow from volcano slopes) that buried part of Armero town
1991: Mount Pinatubo in phillippines

Sources:
http://volcano.oregonstate.edu/how-do-volcanoes-affect-people
https://www.bbc.co.uk/newsround/44100737
https://climate.nasa.gov/faq/42/what-do-volcanoes-have-to-do-with-climate-change/
https://earthdata.nasa.gov/learn/sensing-our-planet/volcanoes-and-climate-change
https://www.ready.gov/volcanoes
