### ISSUE TITLE
Fire Research

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#16]
# Information Needed:

**Comment by antoinella** [comment]
https://docs.google.com/document/d/1HhDPcLerYqtjOExchmvwY8eKk9OMo5I4nqwmJG1BL3Q/edit?usp=sharing

**Comment by rereshek** [comment]
Speed | Example
-- | --
Very slow | The rusting of iron
Slow | The spontaneous heating of materials such as oil soaked rags
Fast | The burning of paper or wood
Extremely fast | The exploding of gunpowder upon ignition

**Comment by rereshek** [comment]
Fire research
Cause: wildfire spreads to residential area / fire from cooking, other electrical equipment or overheating
Effects: destroyed homes, air pollution with harmful to human health chemicals
“During a home fire, there's an increased level of carbon monoxide and carbon dioxide as well as damaging levels of chemical and thermal irritants. These irritants can permanently damage a person's or animal's respiratory system and cause death.”
Emergency response:
Stay low; smoke will rise to ceiling level first.
Drop to hands and knees and crawl toward the nearest exit.
Close the door as you leave the room
Pull the nearest fire alarm (located at any exit)
Hold your breath as much as possible; breathe through your nose and use a filter such as a shirt, towel, or handkerchief.
If trapped, wet and place cloth material around or under the door to help prevent smoke from entering the room.
In kitchen fire: 
Smother the fire by sliding a lid or cookie sheet over the flames and turn the heat source off.
If the flames do not go out, leave your home immediately and call 911 or your local emergency number.
If the fire is small and confined and you choose to fight the fire, ensure all other occupants leave and have a clear way out.
For an oven fire, turn off the heat and keep the door closed until completely cooled.
Remove the fuel (combustible material) from the vicinity of the fire. For example, if you shut off the valve of a gas main, the result will be starvation.
Remove the heat. For example, by applying water, the result will be cooling.
Remove the oxygen. For example, if you cover the fire with a lid, a wet blanket, or some sand, or you use a carbon dioxide, foam, or dry chemical extinguisher, the result is smothering.
Is it linked to climate change: yes
“Another recent study [5] by Flannigan and several other scientists predicts that western Canada will see a 50% increase in the number of dry, windy days that let fires start and spread, whereas eastern Canada will see an even more dramatic 200% to 300% increase in this kind of “fire weather.” Other studies predict that fires could burn twice as much average area per year in Canada by the end of the century as has burned in the recent past.”
The third element that determines the severity of wildfire is dry, windy weather: conditions that Mike Flannigan calls “fire weather”. Dry heat helps create more fuel to burn, and wind both spreads wildfire more rapidly and makes it much harder to put out.
Climate change is stacking the deck so that hot, dry and windy weather shows up more frequently than it used to. Surprisingly, one reason for this increase is the rising temperature of the Arctic.
Where does this happen: Slave Lake, Alberta, British Columbia 

Different levels (magnitudes): 
1) apartment fire (eg overheated pans and pots cause fire)
2) wildfire (massive fires that cause evacuation of hundreds of people)


Speed | Example
-- | --
Very slow | The rusting of iron
Slow | The spontaneous heating of materials such as oil soaked rags
Fast | The burning of paper or wood
Extremely fast | The exploding of gunpowder upon ignition
