### ISSUE TITLE
Proposal - The Pitch (Brief Project Overview)

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#24]
The overview section should contain an introduction providing an outline of the project: the description, project format (installation, physical computing, etc.), methods of user interaction, and any additional required information to convey the idea. It should be succinct and talk about how it relates to themes described in the RFP.

**Comment by antoinella** [comment]
For our project, we propose a collaborative two-player game where both players must work together to find a certain object under a limited timeframe. There will be one player on mobile who is the Professor, and one player in VR who is the Student. The Professor knows exactly which object that the Student needs to find. However, the Student is placed within a large, cluttered environment with many cabinets, shelves, objects, etc. The main clue that the Student will receive is a quick 2D sketch from the Professor, who sees the target object on mobile for a few seconds before it disappears. The Professor will also have access to a bird’s eye view map of the environment, and can tell the Student if their position to the object is “hot” or “cold”.

In terms of project format, we will be using an Android mobile device and a VR headset as our physical tools, as well as Visual Studio Code, A-Frame components, web sockets, Maya, Sculptris, Substance Painter, Adobe Creative Cloud, and GarageBand as our digital tools.

Methods of interaction in this game are different for player 1 (the Professor) and player 2 (the Student). Player 1 is able to use touchscreen to press buttons and draw sketches on their mobile screen. Player 2 can navigate and teleport around their VR environment, as well as pick up objects.

In relation to the themes described in the Request for Proposal (RFP), our project will use immersive VR, multiple users, and multiple devices. Our game will also be educational in terms of promoting collaboration and teamwork among players, since players must work together to achieve a common goal within a short deadline.
