### ISSUE TITLE
Proposal - Audience

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#25]
Short description of your target users and how this experience will reach them.

**Comment by antoinella** [comment]
Our target users are teens and young adults. We chose this age range because most people around this age range begin to experience many group projects in school and at work. It can be a crucial time for them to enhance their teamwork skills. Secondly, our game will be more reachable to users in this age range because they may be more experienced or open to VR and mobile-based games. Thirdly, if our game was to be implemented in a museum, users within this age range would be more likely to play and succeed in this game.

If players have impaired vision, they must wear contacts instead of glasses, particularly when using the VR headset.
