### ISSUE TITLE
Proposal - Key Feature List / Scope 

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#27]
A breakdown of the features/functionality that make up the project. The feature list should be broken down into 3 sections: technical features (e.g. hand tracking), design features (e.g. 4 unique environments), and interaction features (e.g. listing of gestures user can perform). This list is expected to be detailed. Think of the core systems that must be programmed, artwork/design/audio/etc. that must be completed, and the user interaction. Each feature must have a description, and a weighting that defines how important the feature is.

**Comment by antoinella** [comment]
Features | Mobile | Virtual Reality
-- | -- | --
Technical | A-FrameDescription: We will be using A-Frame as a basis to code our game within a virtual environment (Runtime/Javascript Framework/API)Importance: 5 | A-FrameDescription: We will be using A-Frame as a basis to code our game within a virtual environment (Runtime/Javascript Framework/API)Importance: 5
TimerDescription: The two players will win the game if they find the target object under a certain deadline. There will be a small countdown timer displayed on the mobile interface and in the VR environment.Importance: 4
Sending object sketchDescription: The mobile player will quickly sketch out of the target object and press the ‘send’ button once done.Importance: 5 | Receiving object sketchDescription: The VR player receives the object sketch as a JPEG file, loaded into the scene as a texture.Importance: 5
Tracking VR player’s positionDescription: The mobile player can see the VR player’s position as a moving point on a map. The map is a flat, 2D, bird’s eye view of the environment that the VR player is exploring.Importance: 5 | Sending VR player’s positionDescription: The VR player’s position will periodically be sent to the mobile device, so that the mobile map stays updated. That way, the mobile player can see if the VR player is struggling with their direction.Importance: 5
Sending “Hot” or “Cold” hintDescription: Based on the mobile map, the mobile player can see if the VR player is getting closer or further away from the object. The mobile player can hit the “hot” or “cold” button to help the VR player find the object faster.Importance: 4 | Receiving “Hot” or “Cold” hintDescription: The VR player receives the “hot” or “cold” message as a quick text pop-up in their field of view.Importance: 4
Design | 2D environment map(Bird’s eye view)Description: The mobile user has a “God” view of the environment that the VR player is in, except in 2D instead of 3D. The 2D map will be less detailed to highlight wall constraints, the VR player’s position, and the target object’s position.Importance: 5 | 3D modelled environment(First-person view)Description: The 3D modelled environment will be very complex. For example, a large room with many hallways, dead ends, and decorated shelving units. This complex environment will add some challenge to the VR player’s search for the object.Importance: 5
Target objectDescription: The mobile player will see a 3D image of the target object for a few seconds. After, they must sketch the object as accurate as they can and send it to the VR player to find.Importance: 5 | Target object and background objectsDescription: The target object will be 3D modelled with precision. Other objects, that may appear similar, will be 3D modelled to add confusion and challenge to the VR player’s object search.Importance: 5
Background musicDescription: There will be subtle background music that increases in intensity as the timer counts down. This serves as an audio cue to the players that time is running out.Importance: 3
User interface and game buttonsDescription: There will be two different UI screens that the mobile player can alternate between. The first screen will have a canvas to draw on, an option to change the stroke thickness, and a “send drawing” button. The second screen will be the top-perspective map of the VR world, with “hot” and “cold” buttons for the mobile player to give position hints to the VR player.Importance: 4 | Object Sound EffectsDescription: There will be a common sound effect for when objects are picked up/placed down. There will be a distinct sound effect for when the VR player picks up the correct object.Importance: 3
Interaction | Drawing with finger/stylusDescription: The mobile player will draw the object on their phone screen preferably with their finger or using a stylus.Importance: 5 | Grabbing objectsDescription: The VR player will be able to pick up and put down objects to inspect if it is the target object or not.Importance: 5
Pressing buttons with fingerDescription: The mobile player can press buttons on their phone screen preferably with their finger or using a stylus.Importance: 5 |  
Finding target objectDescription: A pop-up displays to indicate to players that they won the game together. There is also a “fun fact” section to teach players about the importance of the target object that they found.Importance: 5
