### ISSUE TITLE
Proposal - Team Member Roles and Bios

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#29]
A listing of the team members and their assigned roles (and secondary roles), as well as short bios to validate role choice. Role crossover is encouraged where possible, but it should be described.

**Comment by antoinella** [comment]
1.6 - Team Member Roles and Bios

Eric Lacey 
Having studied engineering prior to IMD and having just come back from a Coop at IBM as a UX Designer, I use that experience to compliment my IMD skillset. This includes how to act as a project manager, create system structures, facilitate design thinking, and use practical design methodologies.

Primary role: project manager, programmer, editor
		Secondary roles: game mechanics designer

Conor Mulcahy 
I have always been fascinated by the potential of digital media to bring imagination to life, with 3D graphics being the most tangible and immersive way to do so. With this in mind, I am always looking to hone my skills and provide new and exciting experiences to share with others.

	Primary role: 3D modeller, level designer, 3D environment artist
		Secondary roles: UI/UX designer, programmer

Arina Bagdasaryan 
My passion is to create video games and art that people can connect with. I believe that art has the power to change the world therefore I try to pass different ideas or emotions through it so in some way it could influence a potential player. 

		Primary role: concept artist, UI designer, 3D textures artist 
		Secondary roles: level designer

Antoinella Dam
My previous student jobs have given me exposure to the fields of graphic design, video filming, video-editing, photography, and social media. I am excited to apply my experiences to our term project to help enhance our communications, visuals, and audio/music. I also occasionally enjoy designing mock-ups, prototypes, and 3D models, which is why those are my secondary roles.

		Primary role: graphic designer, sound designer, social media marketer, writer
		Secondary roles: UI/UX designer, 3D modeller
