### ISSUE TITLE
Proposal - Wireframes / Storyboards

### ISSUE THREAD

**Issue by EricLacey** [EricLacey/BadWeather#31]
A wireframe must be created for each screen and interface step outlined in the architecture, to help define interaction and user flow. The wireframes should indicate each point of user interaction and clearly outline the information/content presented on screen. Add notes to pages where required to further explain the screen.

**Comment by antoinella** [comment]
2.2 – Wireframes / Storyboards
2.2.1 VR Player
Once mobile/desktop player initializes game, 2D sketch appears in VR player’s initial environment

Figure 4. Once mobile/desktop player is done drawing their sketch, the image of that sketch appears in the 3D environment. Players can always come back to have a look at it. Timer begins for VR player to find the object within 5 minutes.

“Colder” hint appears

Figure 5. When mobile/desktop player presses the “colder” button, VR player’s perspective has a blue overlay to show that they are moving away from the object.

“Hotter” hint appears

Figure 6. When mobile/desktop player presses the “hotter” button, the VR player’s perspective has a red overlay to indicate that they are getting closer to the object.

Picking up object

Figure 7. VR player (student) uses the drawing sketch from mobile/desktop player (Professor) as a reference to select the object that they think is correct from the table.



Collecting and guessing 3D object correctly


Figure 8a. Once VR player collects an object, they must put it in the drop-off zone to evaluate if it is correct. If guessed correctly, a green button lights up and the little display tells the player some interesting information about the object that they found.


Collecting and guessing 3D object incorrectly

Figure 8b. Once VR player collects an object, they must put it in the drop-off zone to evaluate if it is correct. If guessed incorrectly, a red button lights up and the little display tells the player to try again.
2.2.2 Desktop/Mobile Player
Start screen

Figure 9. Mobile/desktop player presses on the button to start the game.


Object appears

Figure 10. Mobile/desktop player sees image of the target object for 5 seconds.





Drawing canvas

Figure 11. After the image of the object disappears, players see a drawing canvas. Players have 30 seconds to redraw the target object. Five colourful circles represent “brush” colour choice, the last circle contains an eraser. If players finish before the timer runs out, they are able to send the image to the VR player using the “send” button in the top left corner. After the timer runs out, the drawing automatically exports into the 3D environment of the 2nd player. Lastly, there is a thumbnail of the object in the bottom-left corner in case the user needs to refer back to it.


Map and buttons

Figure 12. When the sketch is done, the mobile/desktop player sees a top down view of the VR environment, a sprite that depicts the player in VR, a dot that marks the location of the target object and 2 buttons: “colder” and “hotter”. The timer countdown begins. The mobile/desktop player is able to see the movements of the player in VR. Two buttons “colder” and “hotter” exist in order to help to find the target object. If the player in VR approaches towards the target object, the mobile/desktop player should press on the “hotter” button. If the player in VR moves further away from the object, the mobile/desktop player should press on the “colder” button.

“Colder” pressed

Figure 13. When players press the “colder” button, button colour changes to blue.


“Hotter” pressed

Figure 14. When players press the “hotter” button, button colour changes to red.







Game end screen, victory

Figure 15. When the player in VR submits the correct object to the drop-off zone, a window screen pops up. Mobile/desktop player will see the target object on the left and a brief description about it on the right. Also there is a button “try again”, which allows users to play again.

Game end screen, loss
Figure 16. When the player in VR does not submit the correct object to the drop-off zone and the game timer runs out, a window screen pops up. Mobile/desktop player will see the target object on the left and a brief description about it on the right. Also there is a button “try again”, which allows users to play again.

![VR_3](https://user-images.githubusercontent.com/59921079/74362500-d27c0e00-4d96-11ea-8994-12a9d5d25595.png)
![VR_4](https://user-images.githubusercontent.com/59921079/74362501-d27c0e00-4d96-11ea-9821-b99712d0b1a3.png)
![VR_5](https://user-images.githubusercontent.com/59921079/74362503-d314a480-4d96-11ea-96fb-a601181d6f68.png)
![VR_6](https://user-images.githubusercontent.com/59921079/74362504-d314a480-4d96-11ea-99c0-a0ada2decf55.png)
![MobileOrDesktop_1](https://user-images.githubusercontent.com/59921079/74362505-d314a480-4d96-11ea-869a-308ab85037a6.png)
![MobileOrDesktop_2](https://user-images.githubusercontent.com/59921079/74362508-d314a480-4d96-11ea-84bb-18fb6ca0de5b.png)
![MobileOrDesktop_3](https://user-images.githubusercontent.com/59921079/74362509-d314a480-4d96-11ea-817b-48c780180d7b.png)
![MobileOrDesktop_4](https://user-images.githubusercontent.com/59921079/74362510-d3ad3b00-4d96-11ea-8935-2c10d29131cd.png)
![MobileOrDesktop_5](https://user-images.githubusercontent.com/59921079/74362511-d3ad3b00-4d96-11ea-9e98-6c17b2010299.png)
![MobileOrDesktop_6](https://user-images.githubusercontent.com/59921079/74362512-d3ad3b00-4d96-11ea-924f-30a99f287dd3.png)
![MobileOrDesktop_7](https://user-images.githubusercontent.com/59921079/74362513-d3ad3b00-4d96-11ea-9ba8-85fd9559235e.png)
![MobileOrDesktop_8](https://user-images.githubusercontent.com/59921079/74362514-d3ad3b00-4d96-11ea-9508-277c64b14468.png)
![MobileOrDesktop_9](https://user-images.githubusercontent.com/59921079/74362515-d445d180-4d96-11ea-8359-a006243bf17a.png)
![Oculus Rift (VR) pick up obj](https://user-images.githubusercontent.com/59921079/74362516-d445d180-4d96-11ea-9ca0-d2c2ff5929b7.png)
![VR_1](https://user-images.githubusercontent.com/59921079/74362518-d445d180-4d96-11ea-9763-1c0f7942312b.png)
![VR_2](https://user-images.githubusercontent.com/59921079/74362519-d445d180-4d96-11ea-938f-e1c664d1d5a8.png)
